import { Ticket } from "../../models/ticket/ticket";
import { TicketListPayload } from "../../models/ticket/ticket-list-payload";

export const mockTickets: TicketListPayload = {
  status: "ok",
  message: "A message for the user",
  error: "",
  data: {
    tickets: [
      {
        id: "TCK-001",
        idtracking: null,
        idscheduler: 0,
        name: "Some title",
        tags: "tag1,tag2",
        category: "Cleaning",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe",
        project: "Project A",
        building: "Building A 1",
        supplier: "Megaclean",
        floor: "ground floor",
        tenant: "Some tenant",
        timestamp: "2022-09-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-002",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 1",
        tags: "tag1,tag2, tag3",
        category: "Cleaning 1",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 1",
        project: "Project A 1",
        building: "Building A 11",
        supplier: "Megaclean 1",
        floor: "ground floor 1",
        tenant: "Some tenant 1",
        timestamp: "2022-09-19T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-003",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 3",
        tags: "tag1,tag2, tag4",
        category: "Cleaning 3",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 3",
        project: "Project A 3",
        building: "Building A 13",
        supplier: "Megaclean 3",
        floor: "ground floor 3",
        tenant: "Some tenant 3",
        timestamp: "2022-08-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-004",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 4",
        tags: "tag1,tag2,tag5",
        category: "Cleaning 4",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 4",
        project: "Project A 4",
        building: "Building A 14",
        supplier: "Megaclean 4",
        floor: "ground floor 4",
        tenant: "Some tenant 4",
        timestamp: "2022-09-22T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-005",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 5",
        tags: "tag1",
        category: "Cleaning 5",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 5",
        project: "Project A 5",
        building: "Building A 15",
        supplier: "Megaclean 5",
        floor: "ground floor 5",
        tenant: "Some tenant 5",
        timestamp: "2021-09-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-006",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 6",
        tags: "tag2",
        category: "Cleaning 6",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 6",
        project: "Project A 6",
        building: "Building A 16",
        supplier: "Megaclean 6",
        floor: "ground floor 6",
        tenant: "Some tenant 6",
        timestamp: "2022-09-10T18:55:03.540Z",
        approvalKey: "NEW"
      }
    ],
    more: true,
  }
};

export const finalMockTickets: TicketListPayload = {
  status: "ok",
  message: "A message for the user",
  error: "",
  data: {
    tickets: [
      {
        id: "TCK-001",
        idtracking: null,
        idscheduler: 0,
        name: "Some title",
        tags: "tag1,tag2",
        category: "Cleaning",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe",
        project: "Project A",
        building: "Building A 1",
        supplier: "Megaclean",
        floor: "ground floor",
        tenant: "Some tenant",
        timestamp: "2022-09-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-002",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 1",
        tags: "tag1,tag2, tag3",
        category: "Cleaning 1",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 1",
        project: "Project A 1",
        building: "Building A 11",
        supplier: "Megaclean 1",
        floor: "ground floor 1",
        tenant: "Some tenant 1",
        timestamp: "2022-09-19T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-003",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 3",
        tags: "tag1,tag2, tag4",
        category: "Cleaning 3",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 3",
        project: "Project A 3",
        building: "Building A 13",
        supplier: "Megaclean 3",
        floor: "ground floor 3",
        tenant: "Some tenant 3",
        timestamp: "2022-08-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-004",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 4",
        tags: "tag1,tag2,tag5",
        category: "Cleaning 4",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 4",
        project: "Project A 4",
        building: "Building A 14",
        supplier: "Megaclean 4",
        floor: "ground floor 4",
        tenant: "Some tenant 4",
        timestamp: "2022-09-22T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-005",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 5",
        tags: "tag1",
        category: "Cleaning 5",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 5",
        project: "Project A 5",
        building: "Building A 15",
        supplier: "Megaclean 5",
        floor: "ground floor 5",
        tenant: "Some tenant 5",
        timestamp: "2021-09-18T18:55:03.540Z",
        approvalKey: "NEW"
      }, {
        id: "TCK-006",
        idtracking: null,
        idscheduler: 0,
        name: "Some title 6",
        tags: "tag2",
        category: "Cleaning 6",
        statusKey: "NEW",
        priorityKey: "LOW",
        user: "John Doe 6",
        project: "Project A 6",
        building: "Building A 16",
        supplier: "Megaclean 6",
        floor: "ground floor 6",
        tenant: "Some tenant 6",
        timestamp: "2022-09-10T18:55:03.540Z",
        approvalKey: "NEW"
      }
    ],
    more: false,
  }
};

export const mockIndividualTicketsList: Ticket[] = [
  {
    "id": "TCK-001",
    "idtracking": null,
    "idscheduler": 0,
    "name": "Some title",
    "tags": "tag1,tag2",
    "idcategory": 1,
    "category": "Cleaning",
    "attachments": [
      {
        "name": "test.jpeg",
        "type": "image",
        "url": "https://demo.sigtree.com/users/app/uploads/ticket/1234.jpeg"
      }
    ],
    "idstatus": 0,
    "statusKey": "NEW",
    "idpriority": 1,
    "priorityKey": "LOW",
    "iduser": 1,
    "user": "John Doe",
    "idproject": 1,
    "project": "Project A",
    "idbuilding": 1,
    "building": "Building A 1",
    "idsupplier": 1,
    "supplier": "Megaclean",
    "floor": "ground floor",
    "idtenant": 1,
    "tenant": "Some tenant",
    "rating": 5,
    "content": "Ticket description goes here",
    "slaupdatesbreach": 1,
    "timestamp": "2022-09-18T18:55:03.515Z",
    "timestampClosure": "2022-09-18T18:55:03.515Z",
    "timestampResolution": "2022-09-18T18:55:03.515Z",
    "timestampResolutionSLA": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponse": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponseSLA": "2022-09-18T18:55:03.515Z",
    "canClose": 0,
    "idapproval": 0,
    "approvalKey": "NEW"
  }, {
    "id": "TCK-002",
    "idtracking": null,
    "idscheduler": 0,
    "name": "Some title 2",
    "tags": "tag1,tag2",
    "idcategory": 1,
    "category": "Cleaning 2",
    "attachments": [
      {
        "name": "test2.jpeg",
        "type": "image",
        "url": "https://demo.sigtree.com/users/app/uploads/ticket/12342.jpeg"
      }
    ],
    "idstatus": 0,
    "statusKey": "NEW",
    "idpriority": 1,
    "priorityKey": "LOW",
    "iduser": 2,
    "user": "John Doe 2",
    "idproject": 2,
    "project": "Project A 2",
    "idbuilding": 2,
    "building": "Building A 12",
    "idsupplier": 2,
    "supplier": "Megaclean 2",
    "floor": "ground floor 2",
    "idtenant": 2,
    "tenant": "Some tenant 2",
    "rating": 5,
    "content": "Ticket description goes here 2",
    "slaupdatesbreach": 1,
    "timestamp": "2022-09-18T18:55:03.515Z",
    "timestampClosure": "2022-09-18T18:55:03.515Z",
    "timestampResolution": "2022-09-18T18:55:03.515Z",
    "timestampResolutionSLA": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponse": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponseSLA": "2022-09-18T18:55:03.515Z",
    "canClose": 0,
    "idapproval": 0,
    "approvalKey": "NEW"
  }, {
    "id": "TCK-003",
    "idtracking": null,
    "idscheduler": 0,
    "name": "Some title 3",
    "tags": "tag1,tag2",
    "idcategory": 1,
    "category": "Cleaning 3",
    "attachments": [
      {
        "name": "test3.jpeg",
        "type": "image",
        "url": "https://demo.sigtree.com/users/app/uploads/ticket/12343.jpeg"
      }
    ],
    "idstatus": 0,
    "statusKey": "NEW",
    "idpriority": 3,
    "priorityKey": "LOW",
    "iduser": 3,
    "user": "John Doe 3",
    "idproject": 3,
    "project": "Project A 3",
    "idbuilding": 3,
    "building": "Building A 13",
    "idsupplier": 3,
    "supplier": "Megaclean 3",
    "floor": "ground floor 3",
    "idtenant": 3,
    "tenant": "Some tenant 3",
    "rating": 5,
    "content": "Ticket description goes here 3",
    "slaupdatesbreach": 1,
    "timestamp": "2022-09-18T18:55:03.515Z",
    "timestampClosure": "2022-09-18T18:55:03.515Z",
    "timestampResolution": "2022-09-18T18:55:03.515Z",
    "timestampResolutionSLA": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponse": "2022-09-18T18:55:03.515Z",
    "timestampFirstResponseSLA": "2022-09-18T18:55:03.515Z",
    "canClose": 0,
    "idapproval": 0,
    "approvalKey": "NEW"
  }
];

export const ticketPaginationMock: TicketListPayload[] = [mockTickets, mockTickets, mockTickets, finalMockTickets];